In [5]:
import pandas as pd 
import sqlite3
df = pd.read_csv('/Users/hanna/Desktop/superstore-analysis/Superstore.csv', encoding='latin1')
conn = sqlite3.connect(':memory:')
df.to_sql('sales', conn, index = False)
print("Database ready!")

Database ready!

In [7]:
query1 = """
SELECT Category, 
       ROUND(SUM(Sales), 2) as Total_Sales,
       ROUND(SUM(Profit), 2) as Total_Profit
FROM sales
GROUP BY Category
ORDER BY Total_Sales DESC
"""
pd.read_sql_query(query1, conn)

          Category  Total_Sales  Total_Profit
0       Technology    836154.03     145454.95
1        Furniture    741999.80      18451.27
2  Office Supplies    719047.03     122490.80

In [8]:
query2 = """
SELECT Region,
       ROUND(SUM(Sales), 2) as Total_Sales,
       ROUND(SUM(Profit), 2) as Total_Profit,
       ROUND(AVG(Profit), 2) as Avg_Profit
FROM sales
GROUP BY Region
ORDER BY Total_Profit DESC
"""
pd.read_sql_query(query2, conn)

    Region  Total_Sales  Total_Profit  Avg_Profit
0     West    725457.82     108418.45       33.85
1     East    678781.24      91522.78       32.14
2    South    391721.91      46749.43       28.86
3  Central    501239.89      39706.36       17.09

In [11]:
query3 = """
SELECT `Sub-Category`,
       ROUND(SUM(Sales), 2) as Total_Sales,
       ROUND(SUM(Profit), 2) as Total_Profit,
       COUNT(*) as Total_Orders
FROM sales
GROUP BY `Sub-Category`
ORDER BY Total_Profit DESC
LIMIT 10
"""
pd.read_sql_query(query3, conn)

  Sub-Category  Total_Sales  Total_Profit  Total_Orders
0      Copiers    149528.03      55617.82            68
1       Phones    330007.05      44515.73           889
2  Accessories    167380.32      41936.64           775
3        Paper     78479.21      34053.57          1370
4      Binders    203412.73      30221.76          1523
5       Chairs    328449.10      26590.17           617
6      Storage    223843.61      21278.83           846
7   Appliances    107532.16      18138.01           466
8  Furnishings     91705.16      13059.14           957
9    Envelopes     16476.40       6964.18           254

In [12]:
query4 = """
SELECT Category,
       `Sub-Category`,
       COUNT(*) as Loss_Orders,
       ROUND(SUM(Profit), 2) as Total_Loss
FROM sales
WHERE Profit < 0
GROUP BY Category, `Sub-Category`
ORDER BY Total_Loss ASC
LIMIT 10
"""
pd.read_sql_query(query4, conn)

          Category Sub-Category  Loss_Orders  Total_Loss
0  Office Supplies      Binders          613   -38510.50
1        Furniture       Tables          203   -32412.15
2       Technology     Machines           44   -30118.67
3        Furniture    Bookcases          109   -12152.21
4        Furniture       Chairs          235    -9880.84
5  Office Supplies   Appliances           67    -8629.64
6       Technology       Phones          136    -7530.62
7        Furniture  Furnishings          167    -6490.91
8  Office Supplies      Storage          161    -6426.30
9  Office Supplies     Supplies           33    -3015.62

In [13]:
query5 = """
SELECT 
    CASE 
        WHEN Discount = 0 THEN 'No Discount'
        WHEN Discount <= 0.2 THEN 'Low (0-20%)'
        WHEN Discount <= 0.4 THEN 'Medium (20-40%)'
        ELSE 'High (40%+)'
    END as Discount_Level,
    COUNT(*) as Orders,
    ROUND(AVG(Profit), 2) as Avg_Profit,
    ROUND(SUM(Profit), 2) as Total_Profit
FROM sales
GROUP BY Discount_Level
ORDER BY Avg_Profit DESC
"""
pd.read_sql_query(query5, conn)

    Discount_Level  Orders  Avg_Profit  Total_Profit
0      No Discount    4798       66.90     320987.60
1      Low (0-20%)    3803       26.50     100785.47
2  Medium (20-40%)     460      -77.86     -35817.47
3      High (40%+)     933     -106.71     -99558.59